In [3]:
# Import necessary packages
import requests
import urllib.request
import time
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
from urllib.request import urlopen
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [128]:
url = 'https://www.imdb.com/search/title/?title_type=feature&release_date=1950-01-01,2019-12-31&user_rating=8.0,10.0&countries=us&languages=en&sort=year,asc&count=250'
r = requests.get(url)
soup = BeautifulSoup(r.text, 'html.parser')
type(soup)

bs4.BeautifulSoup

In [130]:
movie_containers = html_soup.find_all('div', class_ = 'lister-item mode-advanced')
print(type(movie_containers))

<class 'bs4.element.ResultSet'>

In [132]:
first_movie_name = movie_containers[0].find('h3')
first_movie.a
first_name = first_movie.a.text
first_name

'No Man of Her Own'

In [133]:
names = []
for container in movie_containers:
    name = container.select('img')[0]['alt']
    names.append(name)
names

['No Man of Her Own',
 'Stromboli',
 'Across the Badlands',
 'All About Eve',
 'Armored Car Robbery',
 'The Asphalt Jungle',
 'Atom Man vs. Superman',
 'The Baron of Arizona',
 'Battling Marshal',
 'Born Yesterday',
 'The Breaking Point',
 'Broken Arrow',
 'Caged',
 'Champagne for Caesar',
 'Cheaper by the Dozen',
 'Cinderella',
 'Cyrano de Bergerac',
 "The Damned Don't Cry",
 "Devil's Doorway",
 'Father of the Bride',
 'The Flame and the Arrow',
 'Frisco Tornado',
 'The Furies',
 'The Girl from San Lorenzo',
 "Girls' School",
 'The Glass Menagerie',
 'The Goldbergs',
 'Gun Crazy',
 'The Gunfighter',
 'Harriet Craig',
 'Harvey',
 'House by the River',
 'In a Lonely Place',
 'Kiss Tomorrow Goodbye',
 'The Men',
 'Mister 880',
 'A Modern Marriage',
 "Mrs. O'Malley and Mr. Malone",
 'The Mudlark',
 'Mystery Street',
 'Night and the City',
 'No Way Out',
 'Outside the Wall',
 'Panic in the Streets',
 'Rio Grande',
 'Saddle Tramp',
 'Shakedown',
 'Side Street',
 'Spy Hunt',
 'Stars in My Crown',
 'Stella',
 'Summer Stock',
 'Sunset Blvd.',
 'Three Came Home',
 'Three Little Words',
 'The Sound of Fury',
 'The Underworld Story',
 'Wagon Master',
 'Where the Sidewalk Ends',
 "Winchester '73",
 'Woman on the Run',
 'Young Man with a Horn',
 'Rogue River',
 'The African Queen',
 'Alice in Wonderland',
 'An American in Paris',
 'Angels in the Outfield',
 'Ace in the Hole',
 'Blazing Bullets',
 'The Blue Veil',
 'Bright Victory',
 'Chicago Calling',
 'Come Fill the Cup',
 'Cry Danger',
 'Cuban Fireball',
 'The Day the Earth Stood Still',
 'Death of a Salesman',
 'Decision Before Dawn',
 'Detective Story',
 'The Enforcer',
 'Fighting Coast Guard',
 'Fort Dodge Stampede',
 'Fourteen Hours',
 'Havana Rose',
 'He Ran All the Way',
 'Hello God',
 'The Highwayman',
 'His Kind of Woman',
 'The House on Telegraph Hill',
 "I'll Never Forget You",
 'Kind Lady',
 'The Lemon Drop Kid',
 'Little Egypt',
 'Ma and Pa Kettle Back on the Farm',
 'The Magic Face',
 'The Mating Season',
 'The Mob',
 'The Model and the Marriage Broker',
 'Nevada Badmen',
 'No Highway in the Sky',
 'On Dangerous Ground',
 'On Moonlight Bay',
 'Payment on Demand',
 'Pecos River',
 'People Will Talk',
 'A Place in the Sun',
 'Prairie Roundup',
 'The Prowler',
 'Purple Heart Diary',
 'Quo Vadis',
 'Rawhide',
 'The Red Badge of Courage',
 'Reunion in Reno',
 'The River',
 'Rodeo King and the Senorita',
 'Rough Riders of Durango',
 'The Secret of Convict Lake',
 'Skipalong Rosenbloom',
 'South of Caliente',
 'The Steel Helmet',
 'Storm Warning',
 'Strangers on a Train',
 'A Streetcar Named Desire',
 'The Tall Target',
 'The Thing from Another World',
 "Thunder in God's Country",
 'Tomorrow Is Another Day',
 'Two Gals and a Guy',
 'Up Front',
 'Utah Wagon Train',
 'The Well',
 'Wells Fargo Gunmaster',
 'Westward the Women',
 'When I Grow Up',
 'Whirlwind',
 'The Whistle at Eaton Falls',
 'You Never Can Tell',
 'Othello',
 'Gasoline Alley',
 'Stagecoach Driver',
 'Rhythm Inn',
 'Has Anybody Seen My Gal',
 '5 Fingers',
 'The Bad and the Beautiful',
 'Bend of the River',
 'The Big Sky',
 'Border Saddlemates',
 'Carbine Williams',
 'Carrie',
 'Clash by Night',
 'Come Back, Little Sheba',
 'The Crimson Pirate',
 'Deadline - U.S.A.',
 "Desperadoes' Outpost",
 'The Fabulous Senorita',
 'Fargo',
 'For Men Only',
 'High Noon',
 'Japanese War Bride',
 'Junction City',
 'Just Across the Street',
 'Kansas City Confidential',
 'Leadville Gunslinger',
 'Limelight',
 'The Lusty Men',
 'Ma and Pa Kettle at the Fair',
 'The Marrying Kind',
 'The Maverick',
 'Monkey Business',
 'My Cousin Rachel',
 'The Narrow Margin',
 "O. Henry's Full House",
 'Park Row',
 'Pat and Mike',
 'Phone Call from a Stranger',
 'The Prisoner of Zenda',
 'The Quiet Man',
 'Rancho Notorious',
 'Return of the Texan',
 'Room for One More',
 'Scandal Sheet',
 'Scaramouche',
 "Singin' in the Rain",
 'The Sniper',
 'Son of Geronimo: Apache Avenger',
 'Son of Paleface',
 'The Star',
 'Stars and Stripes Forever',
 'Sudden Fear',
 'Texas City',
 'Thundering Caravans',
 'Tropical Heat Wave',
 'Viva Zapata!',
 'Wait Till the Sun Shines, Nellie',
 'The Yellow Haired Kid',
 'Ma and Pa Kettle on Vacation',
 'The Legend of the Lone Ranger',
 'Angel Face',
 'The Naked Spur',
 '99 River Street',
 "The A-B-C's of Love",
 'All I Desire',
 'The Band Wagon',
 'Bandits of the West',
 'The Big Heat',
 'By the Light of the Silvery Moon',
 'Calamity Jane',
 'Dangerous Crossing',
 'El Paso Stampede',
 'From Here to Eternity',
 'Gentlemen Prefer Blondes',
 'Girls in the Night',
 'The Hitch-Hiker',
 'Hondo',
 'House of Wax',
 'I Confess',
 'Inferno',
 'Julius Caesar',
 'Kiss Me Kate',
 'Lili',
 'Little Boy Lost',
 'Little Fugitive',
 'Man Crazy',
 'Man on a Tightrope',
 'Marry Me Again',
 'Mister Scoutmaster',
 'Niagara',
 'Pack Train',
 'Peter Pan',
 'Pickup on South Street',
 'Rebel City',
 'Red River Shore',
 'Roman Holiday',
 'Savage Frontier',
 'Secret of Outlaw Flats',
 'Shane',
 'Stalag 17',
 'The Story of Three Loves',
 'The Sun Shines Bright',
 'Taxi',
 'Titanic',
 'Topeka',
 'The War of the Worlds',
 'White Lightning',
 'Crime Wave',
 'The Barefoot Battalion',
 'I Love Lucy',
 '20,000 Leagues Under the Sea',
 'About Mrs. Leslie',
 'The Barefoot Contessa']

In [134]:
first_movie_genre_container = movie_containers[0].find('p')
first_movie_genre = first_movie_genre_container.find('span', class_='genre')
first_movie_genre = first_movie_genre.text
first_movie_genre = str(first_movie_genre)
first_movie_genre = first_movie_genre[1:]
first_movie_genre
genres =[]
for container in movie_containers:
    genre_container = container.find('p')
    genre = genre_container.find('span', class_='genre')
    genre = genre.text
    genre = str(genre)
    genre = genre[1:]
    genres.append(genre)
genres[0]

'Drama, Film-Noir            '

In [135]:
#first_movie_genre.find(class = 'genre')
first_year = first_movie.find('span', class_ = 'lister-item-year text-muted unbold')
first_year
years =[]
for container in movie_containers:
    year = container.find('span', class_ = 'lister-item-year').text
    year = str(year)
    year = year[1:5]
    years.append(year)
years[0]

'1950'

In [136]:
first_year = first_year.text
first_year

'(1950)'

In [137]:
names = []
years = []
genres = []
# Extract data from individual movie container
for container in movie_containers:
# Extract:
# The name
    name = container.select('img')[0]['alt']
    names.append(name)
# The year
    year = container.find('span', class_ = 'lister-item-year').text
    year = str(year)
    years.append(year)
    year = str(year)
    year = year[1:5]
# The Genre
    genre_container = container.find('p')
    genre = genre_container.find('span', class_='genre')
    genre = genre.text
    genre = str(genre)
    genre = genre[1:]
    genres.append(genre)

In [138]:
import pandas as pd
test_df = pd.DataFrame({'movie': names,
'year': years,
'name': names,
'genre': genres,
})
print(test_df.info())
test_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 4 columns):
movie    250 non-null object
year     250 non-null object
name     250 non-null object
genre    250 non-null object
dtypes: object(4)
memory usage: 7.9+ KB
None

,movie,year,name,genre
0,No Man of Her Own,(1950),No Man of Her Own,"Drama, Film-Noir"
1,Stromboli,(1950),Stromboli,Drama
2,Across the Badlands,(1950),Across the Badlands,"Action, Comedy, Music"
3,All About Eve,(1950),All About Eve,Drama
4,Armored Car Robbery,(1950),Armored Car Robbery,"Action, Adventure, Crime"
...,...,...,...,...
245,The Barefoot Battalion,(1953),The Barefoot Battalion,"Drama, War"
246,I Love Lucy,(1953),I Love Lucy,Comedy
247,"20,000 Leagues Under the Sea",(1954),"20,000 Leagues Under the Sea","Adventure, Drama, Family"
248,About Mrs. Leslie,(1954),About Mrs. Leslie,"Drama, Romance"
249,The Barefoot Contessa,(1954),The Barefoot Contessa,"Crime, Drama, Mystery"

In [ ]:
https://www.imdb.com/search/title/?title_type=feature&release_date=1950-01-01,2019-12-31&user_rating=7.0,10.0&countries=us&languages=en&sort=year,asc&count=250

In [ ]:
https://www.imdb.com/search/title/?title_type=feature&release_date=1950-01-01,2019-12-31&user_rating=7.0,10.0&countries=us&languages=en&sort=year,asc&count=250&start=251&ref_=adv_nxt

In [ ]:
https://www.imdb.com/search/title/?title_type=feature&release_date=1950-01-01,2019-12-31&user_rating=7.0,10.0&countries=us&languages=en&sort=year,asc&count=250&start=501&ref_=adv_nxt